version: '3.3'
services:
    frontend:
        image: cristianvasile23/idp-proiect:frontend
        tty: true
        stdin_open: true
        ports: 
            - "3000:3000"
        links:
            - server
        networks:
            - idp_network
        
    server:
        image: cristianvasile23/idp-proiect:server
        tty: true
        stdin_open: true
        ports:
            - "4000:4000"
        networks:
            - idp_network

networks: 
    idp_network:
        driver : bridge