version: '3.3'
services:
    frontend:
        # container_name: idp-frontend
        image: cristianvasile23/idp-proiect:frontend
        stdin_open: true
        ports: 
            - "3000:3000"
        # networks:
        #     - idp_network
        
    server:
        # container_name: idp-server
        image: cristianvasile23/idp-proiect:server
        stdin_open: true
        ports:
            - "4000:4000"
        depends_on:
            - db
        environment:
            DB_URL: postgres://admin:password@db:5432/db
            DB_USER: admin
            DB_PASS: password
            DB_NAME: db
        # networks:
        #     - idp_network
            
    db:
        # container_name: idp-db
        image: postgres:12.2-alpine
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-admin}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            POSTGRES_DB: db
        volumes:
            - idp-db-data:/var/lib/postgresql/data
            - ./db_init/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
            - ./db_init/procedures.sql:/docker-entrypoint-initdb.d/2-procedures.sql
        ports:
            - "5432:5432"
        # networks:
        #     - idp_network

    prometheus:
        # container_name: idp-prometheus
        image: prom/prometheus:v2.2.1
        volumes:
            - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        # networks:
        #     - idp_network

    grafana:
        # container_name: idp-grafana
        image: grafana/grafana:5.1.0
        volumes:
            - ./grafana/config.ini:/etc/grafana/grafana.ini
            - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
            - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
            - ./grafana/dashboards:/var/lib/grafana/dashboards
        ports:
            - 2000:3000
#         networks:
#             - idp_network

# networks: 
#     idp_network:
#         driver : bridge

volumes:
    idp-db-data: {}